changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Highlights
      labels:
        - highlight
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Performance
      labels:
        - performance
    - title: Documentation
      labels:
        - documentation
    - title: Developer experience
      labels:
        - developer-experience
        - tooling
    - title: Other changes
      labels:
        - "*"
