"""DataSentry AI core package."""

from importlib.metadata import PackageNotFoundError, version

from datasentry_core.models import (
    AIExplanation,
    AuditEvent,
    BusinessCriticality,
    CauseHypothesis,
    ColumnCheck,
    ColumnContract,
    ColumnDrift,
    ColumnProfile,
    Condition,
    Contract,
    DatasetContract,
    DatasetFingerprint,
    DatasetProfile,
    DetectorRun,
    DriftReport,
    Evidence,
    EvidenceProvenance,
    EvidenceType,
    FeedbackEntry,
    Issue,
    IssueStatus,
    LLMInvocation,
    LLMUsageSummary,
    MaskConfig,
    QualityDimension,
    QualityGate,
    QualityScore,
    RecommendedAction,
    RepairOperation,
    RepairOperationRecord,
    RepairPreview,
    RepairProposal,
    RepairProposalStatus,
    RepairRun,
    RepairRunStatus,
    ReproducibilityInfo,
    RiskLevel,
    RowBeforeAfter,
    Rule,
    RuleCandidate,
    RulePreflightReport,
    RuleType,
    SamplingConfig,
    SamplingInfo,
    ScanConfig,
    ScanRun,
    SchemaChange,
    SemanticEvidence,
    SemanticProfile,
    Severity,
    ValidationResult,
)

__all__ = [
    "AIExplanation",
    "AuditEvent",
    "BusinessCriticality",
    "CauseHypothesis",
    "ColumnCheck",
    "ColumnContract",
    "ColumnDrift",
    "ColumnProfile",
    "Condition",
    "Contract",
    "DatasetContract",
    "DatasetFingerprint",
    "DatasetProfile",
    "DetectorRun",
    "DriftReport",
    "Evidence",
    "EvidenceProvenance",
    "EvidenceType",
    "FeedbackEntry",
    "Issue",
    "IssueStatus",
    "LLMInvocation",
    "LLMUsageSummary",
    "MaskConfig",
    "QualityDimension",
    "QualityGate",
    "QualityScore",
    "RecommendedAction",
    "RepairOperation",
    "RepairOperationRecord",
    "RepairPreview",
    "RepairProposal",
    "RepairProposalStatus",
    "RepairRun",
    "RepairRunStatus",
    "ReproducibilityInfo",
    "RiskLevel",
    "RowBeforeAfter",
    "Rule",
    "RuleCandidate",
    "RulePreflightReport",
    "RuleType",
    "SamplingConfig",
    "SamplingInfo",
    "ScanConfig",
    "ScanRun",
    "SchemaChange",
    "SemanticEvidence",
    "SemanticProfile",
    "Severity",
    "ValidationResult",
]

try:
    __version__ = version("datasentry-core")
except PackageNotFoundError:  # source-tree imports before package installation
    __version__ = "0+unknown"
