"""契约导出器（V1：Pandera / Great Expectations）。

纯函数式：Contract → 外部生态格式（零运行时依赖，不引入
pandera / great_expectations 包）。契约是可移植质量声明的
单一来源，导出使其落地既有数据栈。
"""

from __future__ import annotations

from typing import Any

from datasentry_core.models.contract import ColumnCheck, ColumnContract, Contract
from datasentry_core.models.enums import RuleType
from datasentry_core.models.rules import Rule

#: 语义类型 → Pandera dtype（映射表保持收敛，未知类型回退 object）
_PANDERA_DTYPE = {
    "string": "pa.String()",
    "text": "pa.String()",
    "integer": "pa.Int64()",
    "bigint": "pa.Int64()",
    "float": "pa.Float64()",
    "double": "pa.Float64()",
    "boolean": "pa.Bool()",
    "datetime": "pa.DateTime()",
    "date": "pa.DateTime()",
    "timestamp": "pa.DateTime()",
}

_GE_DTYPE = {
    "string": "String",
    "text": "String",
    "integer": "Integer",
    "bigint": "Integer",
    "float": "Float",
    "double": "Float",
    "boolean": "Boolean",
    "datetime": "DateTime",
    "date": "DateTime",
    "timestamp": "DateTime",
}

#: RuleType → Pandera Check 生成器（value 经 repr 嵌入代码）
_RULE_PANDERA: dict[str, str] = {
    RuleType.VALUE_RANGE.value: "pa.Check.ge({min}) & pa.Check.le({max})",
    RuleType.ALLOWED_VALUES.value: "pa.Check.isin({allowed})",
    RuleType.REGEX.value: "pa.Check.str_matches({pattern})",
    RuleType.NOT_NULL.value: "pa.Check.not_null()",
}


def _pandera_checks(column: ColumnContract, name: str) -> list[str]:
    """列契约 + 内嵌 checks → Pandera Check 表达式列表。"""
    checks: list[str] = []
    if column.min is not None:
        checks.append(f"pa.Check.ge({column.min!r}, title='{name}_min')")
    if column.max is not None:
        checks.append(f"pa.Check.le({column.max!r}, title='{name}_max')")
    if column.allowed_values is not None:
        checks.append(f"pa.Check.isin({column.allowed_values!r}, title='{name}_allowed')")
    if column.regex is not None:
        checks.append(f"pa.Check.str_matches({column.regex!r}, title='{name}_regex')")
    for check in column.checks:
        checks.extend(_pandera_column_check(check, name))
    return checks


def _pandera_column_check(check: ColumnCheck, name: str) -> list[str]:
    """单条 ColumnCheck → Pandera Check 表达式。"""
    if check.type == "regex" and check.pattern:
        return [f"pa.Check.str_matches({check.pattern!r}, title='{name}_check_regex')"]
    if check.type == "range":
        parts = []
        if check.min is not None:
            parts.append(f"pa.Check.ge({check.min!r})")
        if check.max is not None:
            parts.append(f"pa.Check.le({check.max!r})")
        return parts
    if check.type == "allowed_values" and check.allowed_values is not None:
        return [f"pa.Check.isin({check.allowed_values!r}, title='{name}_check_allowed')"]
    if check.type == "not_null":
        return ["pa.Check.not_null()"]
    if check.type == "unique":
        return ["pa.Check.unique()"]
    return []  # custom：不可表达，忽略


def _pandera_rule_check(rule: Rule) -> str | None:
    """顶层 Rule → Pandera Check 表达式；不可表达的返回 None。"""
    if rule.type == RuleType.NOT_NULL:
        return "pa.Check.not_null()"
    if rule.type == RuleType.UNIQUENESS:
        return "pa.Check.unique()"
    if rule.when is None:
        return None
    cond = rule.when
    if rule.type == RuleType.VALUE_RANGE:
        if cond.operator == "between" and isinstance(cond.value, list) and len(cond.value) == 2:
            return f"pa.Check.ge({cond.value[0]!r}) & pa.Check.le({cond.value[1]!r})"
        if cond.operator in ("gte", "lte", "gt", "lt") and isinstance(cond.value, (int, float)):
            op = {"gte": "ge", "lte": "le", "gt": "gt", "lt": "lt"}[cond.operator]
            return f"pa.Check.{op}({cond.value!r})"
        return None
    if rule.type == RuleType.ALLOWED_VALUES and cond.operator == "in":
        if isinstance(cond.value, list):
            return f"pa.Check.isin({cond.value!r})"
        return None
    if rule.type == RuleType.REGEX and cond.operator == "matches" and cond.value:
        return f"pa.Check.str_matches({str(cond.value)!r})"
    return None


def to_pandera(contract: Contract) -> str:
    """Contract → Pandera DataFrameSchema 代码（字符串，用户可复制/执行）。"""
    lines = [
        "import pandera as pa",
        "import pandas as pd",
        "",
        f"# generated by datasentry contract export from dataset: {contract.dataset.name}",
        "# unsupported rules are listed as comments (custom/conditional/aggregate)",
        "schema = pa.DataFrameSchema({",
    ]
    for name, column in contract.columns.items():
        dtype = _PANDERA_DTYPE.get(column.type, "pa.Object()")
        args = [f"    {name!r}: pa.Column("]
        args.append(f"        dtype={dtype},")
        if not column.nullable:
            args.append("        nullable=False,")
        if column.unique:
            args.append("        unique=True,")
        checks = _pandera_checks(column, name)
        for rule in contract.rules:
            if name not in rule.columns:
                continue
            expr = _pandera_rule_check(rule)
            if expr is not None:
                checks.append(expr)
        if checks:
            args.append("        checks=[")
            args.extend(f"            {c}," for c in checks)
            args.append("        ],")
        args.append("    ),")
        lines.extend(args)
    lines.append("})")
    unsupported = [
        f"# unsupported rule '{r.id}' (type={r.type.value})"
        for r in contract.rules
        if _pandera_rule_check(r) is None
    ]
    if unsupported:
        lines.append("")
        lines.extend(unsupported)
    return "\n".join(lines) + "\n"


def _ge_column_expectations(name: str, column: ColumnContract) -> list[dict[str, Any]]:
    """列契约 → GE expect_* 序列。"""
    exps: list[dict[str, Any]] = []
    if column.min is not None or column.max is not None:
        kwargs: dict[str, Any] = {"column": name}
        if column.min is not None:
            kwargs["min_value"] = column.min
        if column.max is not None:
            kwargs["max_value"] = column.max
        exps.append({"expectation_type": "expect_column_values_to_be_between", "kwargs": kwargs})
    if column.allowed_values is not None:
        exps.append(
            {
                "expectation_type": "expect_column_values_to_be_in_set",
                "kwargs": {"column": name, "value_set": column.allowed_values},
            }
        )
    if column.regex is not None:
        exps.append(
            {
                "expectation_type": "expect_column_values_to_match_regex",
                "kwargs": {"column": name, "regex": column.regex},
            }
        )
    for check in column.checks:
        exps.extend(_ge_column_check(name, check))
    if not column.nullable:
        exps.append(
            {
                "expectation_type": "expect_column_values_to_not_be_null",
                "kwargs": {"column": name},
            }
        )
    if column.unique:
        exps.append(
            {
                "expectation_type": "expect_column_values_to_be_unique",
                "kwargs": {"column": name},
            }
        )
    return exps


def _ge_column_check(name: str, check: ColumnCheck) -> list[dict[str, Any]]:
    """单条 ColumnCheck → GE expect_* 序列。"""
    if check.type == "regex" and check.pattern:
        return [
            {
                "expectation_type": "expect_column_values_to_match_regex",
                "kwargs": {"column": name, "regex": check.pattern},
            }
        ]
    if check.type == "range":
        if check.min is None and check.max is None:
            return []
        kwargs: dict[str, Any] = {"column": name}
        if check.min is not None:
            kwargs["min_value"] = check.min
        if check.max is not None:
            kwargs["max_value"] = check.max
        return [
            {
                "expectation_type": "expect_column_values_to_be_between",
                "kwargs": kwargs,
            }
        ]
    if check.type == "allowed_values" and check.allowed_values is not None:
        return [
            {
                "expectation_type": "expect_column_values_to_be_in_set",
                "kwargs": {"column": name, "value_set": check.allowed_values},
            }
        ]
    if check.type == "not_null":
        return [
            {
                "expectation_type": "expect_column_values_to_not_be_null",
                "kwargs": {"column": name},
            }
        ]
    if check.type == "unique":
        return [
            {
                "expectation_type": "expect_column_values_to_be_unique",
                "kwargs": {"column": name},
            }
        ]
    return []


def _ge_rule_expectations(rule: Rule) -> list[dict[str, Any]]:
    """顶层 Rule → GE expect_* 序列。"""
    if not rule.columns:
        return []
    name = rule.columns[0]
    if rule.type == RuleType.NOT_NULL:
        return [
            {
                "expectation_type": "expect_column_values_to_not_be_null",
                "kwargs": {"column": name},
            }
        ]
    if rule.type == RuleType.UNIQUENESS:
        return [
            {
                "expectation_type": "expect_column_values_to_be_unique",
                "kwargs": {"column": name},
            }
        ]
    if rule.when is None:
        return []
    cond = rule.when
    if rule.type == RuleType.VALUE_RANGE:
        if cond.operator == "between" and isinstance(cond.value, list) and len(cond.value) == 2:
            return [
                {
                    "expectation_type": "expect_column_values_to_be_between",
                    "kwargs": {
                        "column": name,
                        "min_value": cond.value[0],
                        "max_value": cond.value[1],
                    },
                }
            ]
        if cond.operator in ("gte", "lte", "gt", "lt") and isinstance(cond.value, (int, float)):
            exp_type = {
                "gte": "expect_column_values_to_be_greater_than_or_equal_to",
                "lte": "expect_column_values_to_be_less_than_or_equal_to",
                "gt": "expect_column_values_to_be_greater_than",
                "lt": "expect_column_values_to_be_less_than",
            }[cond.operator]
            return [{"expectation_type": exp_type, "kwargs": {"column": name, "value": cond.value}}]
        return []
    if rule.type == RuleType.ALLOWED_VALUES and cond.operator == "in":
        if isinstance(cond.value, list):
            return [
                {
                    "expectation_type": "expect_column_values_to_be_in_set",
                    "kwargs": {"column": name, "value_set": cond.value},
                }
            ]
        return []
    if rule.type == RuleType.REGEX and cond.operator == "matches" and cond.value:
        return [
            {
                "expectation_type": "expect_column_values_to_match_regex",
                "kwargs": {"column": name, "regex": str(cond.value)},
            }
        ]
    return []


def to_great_expectations(contract: Contract) -> dict[str, Any]:
    """Contract → GE ExpectationSuite 字典（完整 suite 文档）。"""
    expectations: list[dict[str, Any]] = []
    for name, column in contract.columns.items():
        expectations.extend(_ge_column_expectations(name, column))
        if column.type in _GE_DTYPE:
            expectations.append(
                {
                    "expectation_type": "expect_column_values_to_be_of_type",
                    "kwargs": {"column": name, "type_": _GE_DTYPE[column.type]},
                }
            )
    for rule in contract.rules:
        expectations.extend(_ge_rule_expectations(rule))
    return {
        "expectation_suite_name": f"{contract.dataset.name}.datasentry",
        "expectations": expectations,
        "meta": {
            "datasentry_version": contract.version,
            "dataset": contract.dataset.name,
            "description": contract.dataset.description,
        },
    }
